site_name: Steel Core Documentation
site_author: Rafael de Oliveira Calcada
repo_url: https://github.com/rafaelcalcada/steel-core
markdown_extensions:
    - tables
extra:
    logo: images/steel-logo.svg
theme: 
    name: readthedocs
extra_css: [extra.css]
extra_javascript: [extra.js]
nav:
    - Overview: 'index.md'
    - Getting started: 'getting.md'
    - Configuration: 'config.md'
    - I/O signals: 'steelio.md'
    - Timing diagrams: 'timing.md'
    - Compiling software for Steel: 'software.md'
    - Example system: 'examplesoc.md'
    - Exceptions and interrupts: 'traps.md'
    - Microarchitecture: 'uarch.md'
    - Implementation details: 'details.md'
